using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WD.Library.Utils
{
    /*
     {
        "logid":""  //id of log message, TODO. GUID? or generated by of distributed uniform id generator?
	    "host": "192.168.1.1",    //ip of log host
        "time":"2019-03-20T15:26:47,572", //time stamp
	    "level":"DEBUG", //log level
	    "appid":"100016", //appid
        "stack":"" // call stack
        "version":"",
        "msg":"手机号码错误",
	    "data":{}  //log data
     }

    */

    public class LogMessageModel
    {
        public string traceid
        {
            get; set;
        }

        public string logid
        {
            get;
            set;
        }

        public string host
        {
            get;
            set;
        }

        public DateTime time
        {
            get;
            set;
        }

        public string level
        {
            get;
            set;
        }

        public string appid
        {
            get;
            set;
        }

        //public string stack
        //{
        //    get; set;
        //}
        public string version
        {
            get;
            set;
        }

        public string msg
        {
            get; set;
        }

        public object data
        {
            get;
            set;
        }

        public override string ToString()
        {
            IsoDateTimeConverter timeFormat = new IsoDateTimeConverter();
            timeFormat.DateTimeFormat = "yyyy-MM-dd HH:mm:ss fff";
            var str = JsonHelper.ToJson(this);
            return str;

        }

        public static LogMessageModel Create(string appid, string msg, object businessData = null)
        {
            LogMessageModel model = new LogMessageModel();
            model.appid = appid;
            model.msg = msg;
            model.data = businessData;
            return model;
        }
    }
}
