//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WD.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpressionParserRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpressionParserRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WD.Library.Properties.ExpressionParserRes", typeof(ExpressionParserRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 函数{0}错误，{1} 的本地化字符串。
        /// </summary>
        internal static string FunctionError {
            get {
                return ResourceManager.GetString("FunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \&quot;{0}\&quot;不是DateDiff所支持的时间间隔类型 的本地化字符串。
        /// </summary>
        internal static string InvalidDateDiffType {
            get {
                return ResourceManager.GetString("InvalidDateDiffType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;第{0}的参数类型错误，应该是{1}类型&quot; 的本地化字符串。
        /// </summary>
        internal static string InvalidParameterType {
            get {
                return ResourceManager.GetString("InvalidParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数个数应该不少于{0}个 的本地化字符串。
        /// </summary>
        internal static string InvalidParamsCount {
            get {
                return ResourceManager.GetString("InvalidParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应该有一个&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string peCharExpected {
            get {
                return ResourceManager.GetString("peCharExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现浮点运算越界或除零错误 的本地化字符串。
        /// </summary>
        internal static string peFloatOverflow {
            get {
                return ResourceManager.GetString("peFloatOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现格式错误 的本地化字符串。
        /// </summary>
        internal static string peFormatError {
            get {
                return ResourceManager.GetString("peFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数错误 的本地化字符串。
        /// </summary>
        internal static string peFuncError {
            get {
                return ResourceManager.GetString("peFuncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在非法字符&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string peInvalidChar {
            get {
                return ResourceManager.GetString("peInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在非法操作符&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string peInvalidOperator {
            get {
                return ResourceManager.GetString("peInvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 函数&quot;{0}&quot;应该有{1}个参数 的本地化字符串。
        /// </summary>
        internal static string peInvalidParam {
            get {
                return ResourceManager.GetString("peInvalidParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在非法字符串 的本地化字符串。
        /// </summary>
        internal static string peInvalidString {
            get {
                return ResourceManager.GetString("peInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户自定义函数返回值不能为空 的本地化字符串。
        /// </summary>
        internal static string peInvalidUFValue {
            get {
                return ResourceManager.GetString("peInvalidUFValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要操作数 的本地化字符串。
        /// </summary>
        internal static string peNeedOperand {
            get {
                return ResourceManager.GetString("peNeedOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在语法错误 的本地化字符串。
        /// </summary>
        internal static string peSyntaxError {
            get {
                return ResourceManager.GetString("peSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型不匹配 的本地化字符串。
        /// </summary>
        internal static string peTypeMismatch {
            get {
                return ResourceManager.GetString("peTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在第{0}个字符附近 的本地化字符串。
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
    }
}
